### ISSUE TITLE
Home Assistant 2026.4.0 Problem

### ISSUE THREAD

**Issue by Tanki90** [Schnitzel/hass-miner#595]
With the Version 1.2.7 Update the Integration works with HA Core 2026.3.0 but with HA Core 2026.4.0 i have again a Problem.

## Debug log

 File "/usr/local/lib/python3.14/site-packages/pydantic/_internal/_model_construction.py", line 25, in <module>
    from ._generate_schema import GenerateSchema, InvalidSchemaError
  File "/usr/local/lib/python3.14/site-packages/pydantic/_internal/_generate_schema.py", line 68, in <module>
    from ..functional_validators import AfterValidator, BeforeValidator, FieldValidatorModes, PlainValidator, WrapValidator
  File "/usr/local/lib/python3.14/site-packages/pydantic/functional_validators.py", line 18, in <module>
    from .warnings import ArbitraryTypeWarning, PydanticDeprecatedSince212
ImportError: cannot import name 'PydanticDeprecatedSince212' from 'pydantic.warnings' (/usr/local/lib/python3.14/site-packages/pydantic/warnings.py). Did you mean: 'PydanticDeprecatedSince210'?
2026-04-12 13:34:01.433 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry S19K for miner
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 769, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miner/__init__.py", line 58, in async_setup_entry
    pyasic = await hass.async_add_executor_job(_ensure_pyasic)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/config/custom_components/miner/__init__.py", line 51, in _ensure_pyasic
    import pyasic
  File "/usr/local/lib/python3.14/site-packages/pyasic/__init__.py", line 18, in <module>
    from pyasic import settings
  File "/usr/local/lib/python3.14/site-packages/pyasic/settings/__init__.py", line 21, in <module>
    from pydantic import BaseModel, Field
  File "/usr/local/lib/python3.14/site-packages/pydantic/__init__.py", line 443, in __getattr__
    globals()[attr_name] = result
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/pydantic/main.py", line 36, in <module>
    from ._internal import (
    ...<11 lines>...
    )
  File "/usr/local/lib/python3.14/site-packages/pydantic/_internal/_model_construction.py", line 25, in <module>
    from ._generate_schema import GenerateSchema, InvalidSchemaError
  File "/usr/local/lib/python3.14/site-packages/pydantic/_internal/_generate_schema.py", line 68, in <module>
    from ..functional_validators import AfterValidator, BeforeValidator, FieldValidatorModes, PlainValidator, WrapValidator
  File "/usr/local/lib/python3.14/site-packages/pydantic/functional_validators.py", line 18, in <module>
    from .warnings import ArbitraryTypeWarning, PydanticDeprecatedSince212
ImportError: cannot import name 'PydanticDeprecatedSince212' from 'pydantic.warnings' (/usr/local/lib/python3.14/site-packages/pydantic/warnings.py). Did you mean: 'PydanticDeprecatedSince210'?

```

**Comment by nalditopr** [comment]
Root-caused and fixed in #608. On a fresh container after a Core update every miner config entry runs `uv pip install --upgrade --reinstall pyasic` concurrently; that uninstalls/re-unpacks ~30 shared dependencies (cryptography, pydantic, httpx, …) already imported by Core while sibling entries import a half-written package → `ModuleNotFoundError`/`ImportError`/`AttributeError`, permanent `setup_error`, config flow "Invalid handler specified", or miners that need a manual reload after reboot. #608 serializes the install with a lock and reinstalls only `pyasic` itself.

Workaround until it's merged: after a Core update, restart HA Core once more — the second boot finds pyasic already installed. Or install the branch from https://github.com/nalditopr/hass-miner/tree/fix-pyasic-install-race.
